# references:
# # * http://www.objc.io/issue-6/travis-ci.html
# # * https://github.com/supermarin/xcpretty#usage
#
language: objective-c
osx_image: xcode10

cache:
  directories:
    - $HOME/.cocoapods/

podfile: Example/Podfile

before_install:
#- gem install cocoapods # Since Travis is not always on latest version
#- pod repo update
#- pod install --project-directory=Example
- gem install bundler
- bundle install
# - travis_wait 30 pod repo update --silent
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/AddressGeocoderExample.xcworkspace -scheme AddressGeocoderExampleTests -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' | xcpretty
- pod lib lint
